RUN apk update && \
    apk add --no-cache \
      libx11-xcb \
      libxrandr \
      libxcb \
      libxcomposite \
      libxcursor \
      libxdamage \
      libxfixes \
      libxi \
      libxrender \
      libxss \
      libxtst \
      nss \
      nspr \
      atk \
      at-spi2-atk \
      at-spi2-core \
      gdk-pixbuf \
      gtk+3.0 \
      pango \
      cairo \
      libxcomposite \
      xkeyboard-config \
      libxshmfence
